{% set version = "0.1.6" %}

package:
  name: ratelim
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/ratelim/ratelim-{{ version }}.tar.gz
  sha256: 826d32177e11f9a12831901c9fda6679fd5bbea3605910820167088f5acbb11d

build:
  number: 2
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - decorator

test:
  imports:
    - ratelim

about:
  home: http://github.com/themiurgo/ratelim
  license: MIT
  license_file: LICENSE
  summary: 'Makes it easy to respect rate limits'

extra:
  recipe-maintainers:
    - ocefpaf
